[package]
name = "acpitool"
version = "1.0.0"
authors = ["ssnover95 <ssnover95@gmail.com>"]
edition = "2018"

[dependencies]
acpi_client = "1.0.0"
clap = "2.33.0"

[[bin]]
name = "acpitool"
path = "src/main.rs"

